---
title: "Modelling the relationship between age and body length"
author: "Luke Hayden"
date: "August 3, 2018"
output: html_document
---

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


library(dplyr)
library(ggbiplot)
library(tibble)
library(tidyr)
library(caret)

library(gtools)



powerTransform <- function(y, lambda1, lambda2 = NULL, method = "boxcox") {

  boxcoxTrans <- function(x, lam1, lam2 = NULL) {

    # if we set lambda2 to zero, it becomes the one parameter transformation
    lam2 <- ifelse(is.null(lam2), 0, lam2)

    if (lam1 == 0L) {
      log(y + lam2)
    } else {
      (((y + lam2)^lam1) - 1) / lam1
    }
  }

  switch(method
         , boxcox = boxcoxTrans(y, lambda1, lambda2)
         , tukey = y^lambda1
  )
}
```



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

#setwd("~/Documents/nstringjul18")
load(file="allns_data.rdata")

load(file="sampleinfo.rdata")
zklen <- read.csv("zk-age-len.csv")[2:3] %>%
  mutate(prep="ZK")

lena <- sampleinfo %>%
  filter(!is.na(wkage)) %>%
  select(length, wkage, prep) %>%
  rbind(zklen)


```

#Age-length relationship visualised

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}



ggplot(lena, aes(y=length, x=wkage))+
  geom_point()+
  geom_smooth()+
  theme_bw()+
  scale_colour_brewer(palette="Set1")+
  ggtitle("Age-length relationship in female Parhyale")+
  ylab("Body length (mm)")+
  xlab("Age (weeks)")
  
```

#Model length vs age

We will use the following models:

###Linear regression: age ~ length

Relevant metrics: 
RMSE (lower is better)
R^2 (higher is better)

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

lena$wkage <- as.numeric(lena$wkage)

lena$loglen <- log(lena$length)
lena$lensq <- (lena$length)^2



m <- lm(wkage~length, data=lena)
summary(m)

(bc <- MASS::boxcox(length~wkage, data=lena))

(lambda <- bc$x[which.max(bc$y)])



# re-run with transformation

lena$bctranslen <- powerTransform(lena$length, lambda)
mnew <- lm(wkage~bctranslen, data=lena )
summary(mnew)


lena$linpred <- predict(m)
lena$linresid <- lena$wkage -lena$linpred
lena$bcpred <- predict(mnew)
lena$bcresid <- lena$wkage -lena$bcpred



```



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
polymod2 <- lm(wkage~poly(length,2), data=lena)

lena$polypred2 <- predict(polymod2)

lena$polyresid2 <- lena$wkage -lena$polypred2
````
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
polymod3 <- lm(wkage~poly(length,3), data=lena)

lena$polypred3 <- predict(polymod3)

lena$polyresid3 <- lena$wkage -lena$polypred3
````



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

mlena <- gather(lena, key="model", value="pred", c("bcpred", "linpred", "polypred2", "polypred3"))

# 
# ggplot(mlena, aes(x=pred, y=length, colour=model))+
#   geom_smooth(aes(y=length, x=wkage), colour="orange")+
#   geom_line(size=1, alpha=0.6) +
#   theme_bw()+
#   geom_point(aes(x=wkage), colour="black")+
#   scale_colour_brewer(palette="Set1", labels= c("linear model" ,
#                  "Box-cox transformed linear model", 
#                  "2rd-degree polynomial",
#                  "3rd-degree polynomial")
#                         )+
#   xlab("Age (weeks)")+
#   ylab("Body length (mm)")+
#   ggtitle(label= "Linear regression age vs length", 
#           subtitle=paste0("linear model R-squared: ", round(summary(m)$r.squared, 3), 
#                  "\nBox-cox transformed linear model R-squared: ", round(summary(mnew)$r.squared, 3), 
#                  "\n2rd-degree polynomial R-squared: ", round(summary(polymod2)$r.squared, 2),
#                  "\n3rd-degree polynomial R-squared: ", round(summary(polymod3)$r.squared, 3)))
  
mlena$model <- factor(mlena$model, levels= c( "linpred", "bcpred","polypred2", "polypred3"))


variable_labeller <- function(variable,value){
  return(variable_names[value])
}


variable_names <- list( "linpred"=                   paste("linear model\n R-squared: ", round(summary(m)$r.squared, 3)), 
 "bcpred"=                 paste("Box-cox transformed linear model\n R-squared: ", round(summary(mnew)$r.squared, 3)), 
  "polypred2"=                paste("2rd-degree polynomial\n R-squared: ", round(summary(polymod2)$r.squared, 2)),
    "polypred3" =              paste("3rd-degree polynomial\n R-squared: ", round(summary(polymod3)$r.squared, 3))
                                     )





ggplot(mlena, aes(x=pred, y=length, colour=model))+
  geom_smooth(aes(y=length, x=wkage), colour="orange")+
  geom_line(size=1, alpha=0.6) +
  theme_bw()+
  facet_wrap(~model, labeller=variable_labeller)+
  geom_point(aes(x=wkage), colour="black")+
  scale_colour_brewer(palette="Set1", guide=F)+
  xlab("Age (weeks)")+
  ylab("Body length (mm)")+
  ggtitle("Age vs length models", subtitle= 
            "Models compared with LOESS (orange)")
  
  
  
```


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


mlena <- gather(lena, key="model", value="resid", c("bcresid", "linresid", "polyresid2", "polyresid3"))



mlena$model <- factor(mlena$model, levels= c( "linresid", "bcresid","polyresid2", "polyresid3"))


variable_labeller <- function(variable,value){
  return(variable_names[value])
}


variable_names <- list( "linresid"=                   paste("linear model\n R-squared: ", round(summary(m)$r.squared, 3)), 
 "bcresid"=                 paste("Box-cox transformed linear model\n R-squared: ", round(summary(mnew)$r.squared, 3)), 
  "polyresid2"=                paste("2rd-degree polynomial\n R-squared: ", round(summary(polymod2)$r.squared, 2)),
    "polyresid3" =              paste("3rd-degree polynomial\n R-squared: ", round(summary(polymod3)$r.squared, 3))
                                     )


ggplot(mlena, aes(y=resid, x=length, fill=model, colour=model))+
  geom_bar(stat="identity")+
#  geom_point()+
  scale_colour_brewer(palette="Set1",guide=F)+
  scale_fill_brewer(palette="Set1", labels= c("linear model" ,
                 "Box-cox transformed linear model", 
                 "2rd-degree polynomial",
                 "3rd-degree polynomial")
                        )+
  theme_bw()+
  xlab("Residual Age (weeks)")+
  ylab("Body length (mm)")+
  facet_wrap(~model,labeller=variable_labeller)
````


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

sampleinfo$predage <- NULL
preddf <-subset(sampleinfo, !is.na(sampleinfo$length))

preddf$bctranslen <- powerTransform(preddf$length, lambda)
preddf$predage <-  predict(polymod3, newdata=preddf)


sampleinfo <- left_join(sampleinfo, dplyr::select(preddf, sample, predage), by="sample")


```




```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

save(lena ,m,mnew, polymod2, polymod3, file="lena.rdata")


save(sampleinfo , file="sampleinfo.rdata")

```

