---
title: "Aging effect"
author: "Luke Hayden"
date: "August 3, 2018"
output: html_document
---
#Set-up and data import


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(dplyr)
library(ggbiplot)
library(tibble)
library(tidyr)
library(caret)
library(RColorBrewer)
library(ggrepel)
library(gtools)
library(MASS)
````




```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
#setwd("~/Documents/nstringjul18")
load(file="allns_data.rdata")
load(file="markerchoiceinfo.rdata")

load(file="qualitydat.rdata")
load(file="sampleinfo.rdata")

````



#Old vs Young separation

Old vs young as main groups

##PCA old vs young

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}



log <- sampleinfo$reg == "" & 
  !(sampleinfo$age %in% c("N", "M")) & 
  sampleinfo$sample %in% qualsum$sample[qualsum$good] & 
  sampleinfo$sex == "F"&
  sampleinfo$exp %in% c("OvY", "Size-age") & 
  sampleinfo$ctg > 2 &
  sampleinfo$prep == "Luke"

bcmin <- as.matrix(ctallgood.norm[,log== TRUE])
bcmin.groups <- subset(sampleinfo$type, log==TRUE)

tbc <- as.matrix(t(bcmin))

bc.pca <- prcomp(tbc,center = TRUE,scale. = TRUE) 
bc.groups <- bcmin.groups


ggbiplot(bc.pca, obs.scale = 1, var.scale = 1, ellipse = FALSE, circle = TRUE, var.axes=F, labels=rownames(tbc), groups=bc.groups)+ggtitle("PCA of Old vs Young (females): 50 chosen markers")+
    theme_bw() +
  theme(plot.title=element_text(size=8,face="bold"))+
  scale_colour_manual(values= c("cornflower blue",  "red2"))


````


##PCA old vs young

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
log <- sampleinfo$reg == "" & 
  !(sampleinfo$age %in% c("N", "M")) & 
  sampleinfo$sample %in% qualsum$sample[qualsum$good] & 
  sampleinfo$sex == "F"&
  sampleinfo$exp %in% c("OvY", "Size-age") & 
  sampleinfo$ctg > 2 &
  sampleinfo$prep == "Luke"

bcmin <- t(as.matrix(ctall.norm[,log== TRUE])) %>%
  as.data.frame() %>%
  rownames_to_column(var= "sample") %>%
  left_join(dplyr::select(sampleinfo, sample, type), by= "sample") %>%
  column_to_rownames("sample")

bcmin$type <- factor(bcmin$type)

lda <- lda(formula = type ~ ., 
         data = bcmin, 
         prior = c(1,1)/2)#, CV = TRUE)

lp <- predict(object=lda, newdata=dplyr::select(bcmin, -type))



lpp <- lp$posterior %>%
  as.data.frame() %>%
  rownames_to_column(var= "sample") %>%
  left_join(sampleinfo, by= "sample")

lpp$ldaclass <- lp$class
lpp$iscorrect <- as.character(lpp$type) == as.character(lpp$ldaclass)
  

ggplot(lpp, aes(x=O, fill=type))+
  geom_histogram()+
  ggtitle("LDA of Old vs Young (females): all 195 markers")+
    theme_bw() +
  theme(plot.title=element_text(size=8,face="bold"))+
  scale_fill_manual(values= c("cornflower blue",  "red2"), name= "Age category", labels = c("Old", "Young"))+
  xlab("Old/Young classification posterior probability")


ggplot(lpp, aes(y=O,x=type, color=type, shape=iscorrect))+
  geom_point(size=3, alpha=0.5)+
  ggtitle("PCA of Old vs Young (females): all 195 markers")+
    theme_bw() +
  theme(plot.title=element_text(size=8,face="bold"))+
  scale_color_manual(values= c("cornflower blue",  "red2"), name= "Age category", labels = c("Old", "Young"))+
  scale_shape_manual(values= c(4,16), name= "Accuracy", labels= c("Incorrect", "Correct"))+
  xlab("Age (weeks) from body length") +
  ylab("Old/Young classification posterior probability")
````


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
log <- sampleinfo$reg == "" & 
  !(sampleinfo$age %in% c("N", "M")) & 
  sampleinfo$sample %in% qualsum$sample[qualsum$good] & 
  sampleinfo$sex == "F"&
  sampleinfo$exp %in% c("OvY", "Size-age") & 
  sampleinfo$ctg > 2 &
  sampleinfo$prep == "Luke"

bcmin <- t(as.matrix(ctallgood.norm[,log== TRUE])) %>%
  as.data.frame() %>%
  rownames_to_column(var= "sample") %>%
  left_join(dplyr::select(sampleinfo, sample, type), by= "sample") %>%
  column_to_rownames("sample")

bcmin$type <- factor(bcmin$type)

lda <- lda(formula = type ~ ., 
         data = bcmin, 
         prior = c(1,1)/2)#, CV = TRUE)

lp <- predict(object=lda, newdata=dplyr::select(bcmin, -type))



lpp <- lp$posterior %>%
  as.data.frame() %>%
  rownames_to_column(var= "sample") %>%
  left_join(sampleinfo, by= "sample")

lpp$ldaclass <- lp$class
lpp$iscorrect <- as.character(lpp$type) == as.character(lpp$ldaclass)
  


ggplot(lpp, aes(x=O, fill=type))+
  geom_histogram()+
  ggtitle("LDA of Old vs Young (females): 50 markers")+
    theme_bw() +
  theme(plot.title=element_text(size=8,face="bold"))+
  scale_fill_manual(values= c("cornflower blue",  "red2"), name= "Age category", labels = c("Old", "Young"))+
  xlab("Old/Young classification posterior probability")


ggplot(lpp, aes(y=O,x=type, color=type, shape=iscorrect))+
  geom_point(size=3, alpha=0.5)+
  ggtitle("PCA of Old vs Young (females): 50 markers")+
    theme_bw() +
  theme(plot.title=element_text(size=8,face="bold"))+
  scale_color_manual(values= c("cornflower blue",  "red2"), name= "Age category", labels = c("Old", "Young"))+
  scale_shape_manual(values= c(4,16), name= "Accuracy", labels= c("Incorrect", "Correct"))+
  xlab("Age (weeks) from body length") +
  ylab("Old/Young classification posterior probability")
````



#Old vs young by marker

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


md <- t(subset(t(ctall.norm), sampleinfo$sex == "F" &
  #              sampleinfo$qual == "ok"& 
                 sampleinfo$exp %in% c("OvY", "Size-age", "cohorts") & 
                 sampleinfo$ctg>2 & 
                sampleinfo$codeset == "phaw_1" &
                 sampleinfo$type %in% c("O", "Y", "M")& 
  !(sampleinfo$sample %in% c("T","C", "U", "LFPD", "O1a", "SFPA", "LFIB","LFIA","AF", "Coh8"))))

si <- subset(sampleinfo, sampleinfo$sample %in% colnames(md))
old <- t(subset(t(md), si$age == "O"))
young <- t(subset(t(md), si$age == "Y"))
#regen <- t(subset(t(ctg1to9), sampleinfo$type == "OR" & sampleinfo$qual != "bad"))





nmd <- as.data.frame(md/rowMeans(md))


ns <- colnames(md)

nmd$name <- rownames(md)
nmd$sname <- substr(nmd$name, 1,2)


sl <- as.character(sampleinfo$sample[sampleinfo$sample %in% colnames(nmd)])

mmd <- gather(as.data.frame(md), key="sample", value="expression", sl)

mnmd <- gather(nmd, key="sample", value="normexp", sl) %>%
  left_join(sampleinfo, by= "sample") %>%
  left_join(mmd, by="sample")


ggplot(mnmd, aes(x= sname, y=normexp, colour=type))+
#  geom_point()+
  theme_bw()+
  geom_boxplot(outlier.shape=NA)+
  scale_y_continuous(trans="log2")+
  facet_grid(~dir, space="free",scales="free" )+
#  geom_boxplot(outlier.shape = NA)+
  scale_colour_manual(values=c("darkviolet", "cornflower blue", "red3"))+
  scale_fill_manual(values=c("darkviolet", "cornflower blue", "red3"))+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  ylab("Normalised Expression") +
  xlab('Marker')
  


````

##What markers best separate old vs young?

Build linear regression for the expression of each marker vs age (based on size)

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

md <- as.data.frame(subset(t(ctall.norm), sampleinfo$sex == "F" &
  #              sampleinfo$qual == "ok"& 
#                 sampleinfo$exp %in% c("OvY", "Size-age", "cohorts") & 
                 sampleinfo$ctg>2 & 
                sampleinfo$codeset == "phaw_1" &
                 sampleinfo$type %in% c("O", "Y", "M")))
 # !(sampleinfo$sample %in% c("T","C", "U", "LFPD", "O1a", "SFPA", "LFIB","LFIA","AF", "Coh8"))))



markerlist <- colnames(md)

md$sample <- rownames(md)


md <- left_join(md, select(sampleinfo, sample, predage), by="sample") %>%
  filter(!(is.na(predage))) %>%
  column_to_rownames(var="sample")



lmlist <- list()
arsqlist <- list()
rselist <- list()
plist <- list()
rmselist <- list()


for (i in 1:length(markerlist)){
  ilm <- lm(as.formula(paste0("predage~", markerlist[i])), md)
  lmlist[i] <- ilm
  arsqlist[i]<- summary(ilm)$adj.r.squared
  rmselist[i] <- sqrt(sum(residuals(ilm)^2) / df.residual(ilm))
  
  
}


lmdf <- data.frame(name =markerlist, rsq=unlist(arsqlist), rmse=unlist(rmselist)) %>%
  left_join(geneinf, by="name")


lmdf$sname <- substr(lmdf$name, 1,2)
lmdf$sname <- factor(lmdf$sname, levels=lmdf$sname[order(lmdf$rsq)])


ggplot(lmdf, aes(x=sname, y=rsq, fill=in61))+
  theme_bw()+
  geom_bar(stat="identity")+
  ylab("R-squared \n (linear regression age vs expression)")+
  xlab("Marker")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size=4))




````



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

md <- t(subset(t(ctall.norm), sampleinfo$sex == "F" &
               sampleinfo$qual == "ok"& 
 #                sampleinfo$exp %in% c("OvY", "Size-age", "cohorts") & 
                 sampleinfo$ctg>2 & 
   sampleinfo$ctg <5 &
                sampleinfo$codeset == "phaw_1" &
                 sampleinfo$type %in% c("O", "Y", "M")&
 !(sampleinfo$sample %in% c("T","C", "U", "LFPD", "O1a", "SFPA", "LFIB","LFIA","AF", "Coh8"))
  
  
  ))

si <- subset(sampleinfo, sampleinfo$sample %in% colnames(md))
old <- t(subset(t(md), si$age == "O"))
young <- t(subset(t(md), si$age == "Y"))
#regen <- t(subset(t(ctg1to9), sampleinfo$type == "OR" & sampleinfo$qual != "bad"))



oy <- cbind(old, young)
t.result <-  apply(oy, 1, function (x) t.test(x[1:ncol(old)],x[ncol(old)+1: ncol(oy)]))


pvals <- data.frame(name=rownames(md), pvalovy = unlist(lapply(t.result, function(x) x$p.value)))



lmdf2 <- left_join(lmdf, pvals, by="name")
pthresh <- 0.05

ggplot(lmdf2, aes(x=pvalovy, y=rsq, fill=in61, label=name))+
  theme_bw()+
  geom_point(shape=21)+
  scale_x_log10()+
  geom_vline(x=pthresh, xintercept = pthresh, linetype=2)+
  ggtitle(paste(length(lmdf$name[
      lmdf2$pvalovy <pthresh]), "markers with significant old vs young p-value"))+ 
  xlab("Old vs young p-value")+
  ylab("R-squared \n (linear regression age vs expression)")



```


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

md <- t(subset(t(ctall.norm), sampleinfo$sex == "F" &
  #              sampleinfo$qual == "ok"& 
                 sampleinfo$exp %in% c("OvY", "Size-age", "cohorts") & 
                 sampleinfo$ctg>2 & 
                sampleinfo$codeset == "phaw_1" &
                 sampleinfo$type %in% c("O", "Y", "M")& 
  !(sampleinfo$sample %in% c("T","C", "U", "LFPD", "O1a", "SFPA", "LFIB","LFIA","AF", "Coh8"))))

si <- subset(sampleinfo, sampleinfo$sample %in% colnames(md))
old <- t(subset(t(md), si$age == "O"))
young <- t(subset(t(md), si$age == "Y"))
#regen <- t(subset(t(ctg1to9), sampleinfo$type == "OR" & sampleinfo$qual != "bad"))





nmd <- as.data.frame(md/rowMeans(md))


ns <- colnames(md)

nmd$name <- rownames(md)
nmd$sname <- substr(nmd$name, 1,2)

oy <- cbind(old, young)
t.result <-  apply(oy, 1, function (x) t.test(x[1:ncol(old)],x[ncol(old)+1: ncol(oy)]))



nmd$p_value <- unlist(lapply(t.result, function(x) x$p.value))

nmd <- left_join(nmd, geneinf, by="name")






nmd$YvOl2fc <- foldchange2logratio(foldchange(rowMeans(young), rowMeans(old)))


nmd$sname <- factor(nmd$sname, levels=nmd$sname[order(nmd$YvOl2fc)])
nmd$good <- nmd$p_value <0.05
nmd$di <- paste0(ifelse(nmd$dir == "upregulated with age", "up", "down"), ": ", nmd$sname)


#nmd <- as.data.frame(md/rowMeans(md))



````



##Expression/age regression


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
mnmd <- gather(nmd, key="sample", value="normexp", ns)


mnmd <- left_join(mnmd, sampleinfo, by="sample")

mnmd<- subset(mnmd, (!is.na(predage))) %>%
  left_join(select(minf, sname, chosenand), by="sname") %>%
  left_join(select(lmdf2, name, rsq, rmse, pvalovy), by="name")

mnmd$grsq <- mnmd$rsq > 0.06

mnmd$ca <- ifelse(mnmd$chosenand == T, "amongst chosen 50", "not amongst chosen 50")

ggplot(mnmd, aes(x=predage, y=normexp))+
#  geom_point(shape=21, aes(fill=type))+
#  geom_text(aes(label=sample, colour=type))+
   geom_smooth(method="lm", se=F, aes(size=sname, colour=grsq),alpha=0.3,linetype=1)+
  scale_size_manual(values=rep(0.5,195), guide=F)+
  theme_bw()+
#scale_y_continuous(trans="log2")+
 scale_fill_manual(values=c("darkviolet", "cornflower blue", "red3"))+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  ylab("Normalised Expression") +
#  xlab('pre')+
  facet_grid(dir~ca)+
  scale_colour_manual(values=c("grey", "forest green"))


grsq <- unique(mnmd$name[mnmd$rsq>0.04])
```




#Old vs young by marker

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

sl <- as.character(sampleinfo$sample[sampleinfo$sample %in% colnames(nmd)])

mmd <- gather(as.data.frame(md), key="sample", value="expression", sl)

mnmd <- gather(nmd, key="sample", value="normexp", sl) %>%
  left_join(sampleinfo, by= "sample") %>%
  left_join(mmd, by="sample")


ggplot(mnmd, aes(x= sname, y=normexp, colour=type))+
#  geom_point()+
  theme_bw()+
  geom_boxplot(outlier.shape=NA)+
  scale_y_continuous(trans="log2")+
  facet_grid(~dir, space="free",scales="free" )+
#  geom_boxplot(outlier.shape = NA)+
  scale_colour_manual(values=c("darkviolet", "cornflower blue", "red3"))+
  scale_fill_manual(values=c("darkviolet", "cornflower blue", "red3"))+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  ylab("Normalised Expression") +
  xlab('Marker')
  


````



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


mnmd2 <- subset(mnmd,mnmd$name %in% minf$name[ minf$chosenand ==T])


ggplot(mnmd2, aes(x= sname, y=normexp, colour=type))+
#  geom_point()+
  theme_bw()+
  geom_boxplot(outlier.shape=NA)+
  scale_y_continuous(trans="log2")+
  facet_grid(~dir, space="free",scales="free" )+
#  geom_boxplot(outlier.shape = NA)+
  scale_colour_manual(values=c("darkviolet", "cornflower blue", "red3"))+
  scale_fill_manual(values=c("darkviolet", "cornflower blue", "red3"))+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  ylab("Normalised Expression") +
  xlab('Marker')
  
````



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

md <- as.data.frame(subset(t(ctall.norm), sampleinfo$sex == "F" &
                sampleinfo$qual == "ok"& 
 #                sampleinfo$exp %in% c("Size-age", "cohorts", "OvY") & 
 #                sampleinfo$ctg>2 & 
                    sampleinfo$prep== "Luke"&
                sampleinfo$codeset == "phaw_1" &
                 sampleinfo$type %in% c("OR")& 
  !(sampleinfo$sample %in% c("Areg"))))


cvdf <- data.frame(name= colnames(md), 
 regencv = coefficient.variation(colMeans(md), apply(md,2, sd)))
```
