---
title: "gbmfullopt5"
author: "Luke Hayden"
date: "16 September 2019"
output: html_document
---



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

#Set-up and data import
library(dplyr)
library(tibble)
library(tidyr)
library(caret)
library(RColorBrewer)
library(ggrepel)
library(gtools)
#library(FinCal)
````




```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
#setwd("~/Documents/nstringjul18")
load(file="allns_data.rdata")
load("vardat.rdata")

load(file="qualitydat.rdata")
load(file="sampleinfo.rdata")
load(file="markerchoiceinfo.rdata")

load(file="gbmrsqopt.rdata")
      
load(file="lena.rdata")
load(file="gbmrmseopt.rdata") 
load("fullns_data.rdata")
load(file="qualitydat.rdata")
load(file="qualitydatwnew.rdata")

````

#Choose model samples



```{r Gradient boosting build, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
uns<-  sampleinfoc$sample[
                sampleinfoc$sex == "F" &              
                  sampleinfoc$prep== "Luke"&
                  sampleinfoc$reg == "" &
                 sampleinfoc$exp %in% c("regen", "regen-long") &
                 sampleinfoc$type %in% c("O", "Y", "M")
] %>%
  as.character()

uns <- uns[grepl("un", uns)]


names <- substr(uns,1,nchar(uns)-2)


regs<-  sampleinfoc$sample[
                sampleinfoc$sex == "F" &              
                  sampleinfoc$prep== "Luke"&
                  sampleinfoc$reg %in% c("R", "R-A") &
                 sampleinfoc$exp %in% c("regen", "regen-long") 
] %>%
  as.character()

badregs <- qualsum$sample[
  qualsum$sample %in% regs &
  qualsum$good == F
] %>%
  as.character()

baduns <- paste0(substr(badregs,1,nchar(badregs)-3), "un")


#regs <- substr(regs,1,nchar(regs)-2)





````



```{r Gradient boosting build, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

sampleinfob <- read.csv("sialplus.csv")


mymodel <- gbmrmseopt


sampleinfoc <- subset(sampleinfob, sampleinfob$sample %in% colnames(ctfull.norm))




markexp <-  data.frame( marker = colnames(t(ctfull.norm)), 
                        meanexp = colMeans(t(ctfull.norm), na.rm = T))


md <- as.data.frame(subset(t(ctfull.norm), 
                sampleinfoc$sex == "F" &              
                  sampleinfoc$prep== "Luke"&
                 sampleinfoc$exp %in% c("Size-age", "cohorts", "OvY") &
                 sampleinfoc$type %in% c("O", "Y", "M")
))

md2 <- as.data.frame(subset(t(ctfull.norm),                             sampleinfoc$sample %in% baduns))
                      

md <- rbind(md, md2)

md <-subset(md, rownames(md)%in% qualsum$sample[qualsum$good])

md <- md[,colnames(md) %in% mymodel$coefnames]


thresh <- 30

md <- md[,colnames(md) %in% markexp$marker[markexp$meanexp > thresh]]



md2 <- as.data.frame(md) %>%
  rownames_to_column(var ="sample") %>%
  left_join(sampleinfoc, by="sample")

predage <- predict(polymod3, newdata=md2)

md$predage <- predage
md <- subset(md, !(is.na(md$predage)))


md <- subset(md, rownames(md)%in% qualsum$sample[qualsum$good])

trainchoice <- sample(1:nrow(md))[1:ceiling(4*(nrow(md)/5))]



#currbest <- gbmfullrsqinc2




#trainchoice <- rownames(md) %in% rownames(currbest$trainingData)




trdat<- md[trainchoice,]

```



```{r Gradient boosting build, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
rffullrsq <- train(form = predage ~ .,
                        data = trdat, 
                        tuneLength = 4, 
    method = "gbm",
    metric = "Rsquared", 
    tuneGrid = expand.grid(
      n.trees = (0:50) * 100, 
        interaction.depth = c(1, 2, 3, 4, 5), 
        shrinkage = c(1e-04, 0.001, 0.01, 0.1), 
        n.minobsinnode = c(1,2, 3, 4, 5, 6, 7,8,10)
      ), 
    trControl = trainControl(
      method = "cv",
      number = 5, 
      summaryFunction = defaultSummary, 
      verboseIter = F)
    )



save(gbmfullrsqinc8, file="gbmfullrsqinc8.rdata")
```



```{r Gradient boosting build, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
gbmfullrsqcompro8 <- train(
  form = predage ~ .,
  data = trdat, 
  tuneLength = 4, 
    method = "gbm",
 #   metric = "Rsquared", 
    tuneGrid = expand.grid(
      n.trees = (0:50) * 100, 
        interaction.depth = c(1, 2, 3, 4, 5), 
        shrinkage = c(1e-04, 0.001, 0.01, 0.1), 
        n.minobsinnode = c(1,2, 3, 4, 5, 6, 7,8,10)
      ), 
    trControl = trainControl(
      method = "cv",
      number = 6, 
      summaryFunction = defaultSummary, 
      verboseIter = F)
    )



save(gbmfullrsqcompro8, file="gbmfullrsqcompro8.rdata")
```