---
title: "Ammene ton CARTable!"
author: "Luke Hayden"
date: "8 Novembre 2018"
output:
  html_document:
    df_print: paged
  beamer_presentation:
    colortheme: fly
    fonttheme: default
    theme: Darmstadt
slide_level: 3
---



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(reshape2)
library(ggbiplot)
library(tibble)
library(tidyr)
library(caret)
library(RColorBrewer)
library(ggrepel)
library(gtools)
library(FinCal)
library(ggrepel)

library(dplyr)
#library(e10)
````



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
#setwd("~/Documents/nstringjul18/nstringfull")
load(file="allns_data.rdata")
load(file="modelrf.rdata")
load(file="modelgbm.rdata")
load(file="hkdat.rdata")
load(file="sampleinfo.rdata")
load(file="qualitydat.rdata")
load(file="vardat.rdata")
load(file="goodgroups.rdata")
load(file="markerchoiceinfo.rdata")

load(file="lena.rdata")
load(file="progmodels.rdata")
load(file="rfagemodelbadcv.rdata")


````

#Project

Examine the effect of regeneration on the molecular age profile of *Parhyale* limbs

##Designing codeset

*Nanostring as method to quantify gene expression

*200 genes in codeset

-195 genes chosen on the basis of differential expression analysis 

-5 control genes: do not vary in expression between conditions

#Age-length relationship
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

mlena <- gather(lena, key="model", value="pred", c("bcpred", "linpred", "polypred2", "polypred3"))

# 
# ggplot(mlena, aes(x=pred, y=length, colour=model))+
#   geom_smooth(aes(y=length, x=wkage), colour="orange")+
#   geom_line(size=1, alpha=0.6) +
#   theme_bw()+
#   geom_point(aes(x=wkage), colour="black")+
#   scale_colour_brewer(palette="Set1", labels= c("linear model" ,
#                  "Box-cox transformed linear model", 
#                  "2rd-degree polynomial",
#                  "3rd-degree polynomial")
#                         )+
#   xlab("Age (weeks)")+
#   ylab("Body length (mm)")+
#   ggtitle(label= "Linear regression age vs length", 
#           subtitle=paste0("linear model R-squared: ", round(summary(m)$r.squared, 3), 
#                  "\nBox-cox transformed linear model R-squared: ", round(summary(mnew)$r.squared, 3), 
#                  "\n2rd-degree polynomial R-squared: ", round(summary(polymod2)$r.squared, 2),
#                  "\n3rd-degree polynomial R-squared: ", round(summary(polymod3)$r.squared, 3)))
  
mlena$model <- factor(mlena$model, levels= c( "linpred", "bcpred","polypred2", "polypred3"))


variable_labeller <- function(variable,value){
  return(variable_names[value])
}


variable_names <- list( "linpred"=                   paste("linear model\n R-squared: ", round(summary(m)$r.squared, 3)), 
 "bcpred"=                 paste("Box-cox transformed linear model\n R-squared: ", round(summary(mnew)$r.squared, 3)), 
  "polypred2"=                paste("2rd-degree polynomial\n R-squared: ", round(summary(polymod2)$r.squared, 2)),
    "polypred3" =              paste("3rd-degree polynomial\n R-squared: ", round(summary(polymod3)$r.squared, 3))
                                     )





ggplot(mlena, aes(x=pred, y=length, colour=model))+
  geom_smooth(aes(y=length, x=wkage), colour="orange")+
  geom_line(size=1, alpha=0.6) +
  theme_bw()+
  facet_wrap(~model, labeller=variable_labeller)+
  geom_point(aes(x=wkage), colour="black")+
  scale_colour_brewer(palette="Set1", guide=F)+
  xlab("Age (weeks)")+
  ylab("Body length (mm)")+
  ggtitle("Age vs length models", subtitle= 
            "Models compared with LOESS (orange)")
  
  
  
```