---
title: "images for Michalis pres"
---



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(reshape2)
library(ggbiplot)
library(tibble)
library(tidyr)
library(caret)
library(RColorBrewer)
library(ggrepel)
library(gtools)
library(FinCal)
library(ggrepel)

library(dplyr)
#library(e10)
````



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
p=ggplot(lena, aes(x=polypred3, y=length))+
  geom_smooth(aes(y=length, x=wkage), colour="orange", se=F)+
  geom_line(size=1, alpha=0.6, colour="forest green") +
  theme_bw()+
#  facet_wrap(~model, labeller=variable_labeller)+
  geom_point(aes(x=wkage), colour="black")+
  scale_colour_brewer(palette="Set1", guide=F)+
  xlab("Age (weeks)")+
  ylab("Body length (mm)")+
  ggtitle("Age vs length model", subtitle= paste("3rd-degree polynomial\nR-squared: ", round(summary(polymod3)$r.squared, 3), 
            "\ncompared with LOESS (orange)"))+
  theme(
    plot.background = element_rect(fill = "transparent",colour = "transparent") # bg of the panel
  )
  
  

ggsave(plot=p,height=4,width=6,dpi=200, filename=paste("polynomial.png"),device="png",  limitsize = FALSE)


  
```



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
mymodel <- currbest
#mymodel <- rfagemodel

md <- as.data.frame(subset(t(ctall.norm), sampleinfo$sex == "F" &
#               sampleinfo$qual == "ok"&
                 sampleinfo$prep== "Luke"&
                 sampleinfo$exp %in% c("Size-age", "cohorts", "OvY") &
 #                sampleinfo$ctg>2 &
                sampleinfo$codeset == "phaw_1" &
                 sampleinfo$type %in% c("O", "Y", "M")
))

md <- subset(md, rownames(md)%in% qualsum$sample[qualsum$good])

md <- md[,colnames(md) %in% mymodel$coefnames]



md$rfagepred <- predict(mymodel, newdata=md)


md$intrain <- rownames(md) %in% rownames(mymodel$trainingData)



md <- md %>%
  rownames_to_column(var="sample") %>%
  left_join(sampleinfo,  by="sample")

md <- subset(md, !(is.na(md$predage)))


RMSEtr <- sqrt(mean( (md$rfagepred[md$intrain == T] - md$predage[md$intrain == T])   ^2))





RMSEte <- sqrt(mean( (md$rfagepred[md$intrain == F] - md$predage[md$intrain == F])   ^2))

(p=ggplot(md, aes(x=predage, y=rfagepred,colour=intrain))+
  geom_point()+
  xlab("Age (weeks) inferred from body length") +
  ylab("Age (weeks) inferred from marker gene expression (random forest model)")+
  geom_smooth(method="lm", colour="black")+
  theme_bw()+
 scale_colour_manual(values=c("cornflower blue", "red3"), name="Data partition", labels=c("Test", "Training"))+
  geom_text_repel(aes(label=sample), size=2.5)+
  ggtitle("Using random forest model to predict age from gene expression", 
          subtitle=paste0("RMSE in training data: ", round(RMSEtr,3), 
                          "\nRMSE in test data: ", round(RMSEte,3))))#+  facet_wrap(~intrain)


#ggsave(plot=p,height=5,width=6,dpi=200, filename=paste("modeltrte.pdf"), useDingbats=FALSE, limitsize = FALSE)


```

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}



````