---
title: "qual"
author: "Luke Hayden"
date: "July 26, 2018"
output: html_document
---



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(dplyr)
library(ggbiplot)
library(tibble)
library(tidyr)
library(reshape2)
library(matrixStats)
library(gtools)
library(GGally)
```




```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
#setwd("~/Documents/nstringjul18")
load(file="allns_data.rdata")
load(file="sampleinfo.rdata")
````



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


mc <- melt(ctall.norm/rowMeans(ctall.norm, na.rm=T))
colnames(mc) <- c("marker", "sample", "expression")
mc <- left_join(mc, sampleinfo, by= "sample") %>%
#  left_join(posdf, by= "sample") %>%
  mutate(ctgsamp= paste0(ctg,"  ",  sample, ": ", over10reads  ))



# (p=ggplot(mc, aes(x=marker, y=expression, colour=over0reads)) +geom_point() +
#   facet_wrap(~ctgsamp, ncol=6)+
#     scale_y_log10()+
#     scale_colour_gradient(high="green", low="red2")+
#     theme_minimal()
#   )
#   
# ggsave(plot=p, filename = "qual.pdf", device="pdf", height=40, width=6, limitsize = F)
#   

````

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
hkdat <- as.data.frame(t(ctall.hk))

nhkdat <- t(ctall.hk/rowMeans(ctall.hk))

meds <- colMedians(t(ctall.hk))


hkdat$over1 <- rowSums(hkdat>0)
hkdat$over3 <- rowSums(t(ctall.hk)>3)

hkdat$over5 <- rowSums(t(ctall.hk)>5)


hkdat$over10 <- rowSums(t(ctall.hk)>10)

hkdat$sample <- rownames(hkdat)

````



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
save(hkdat, file="hkdat.rdata")

````



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


md <- as.data.frame(t(subset(t(ctall.norm), 
                 sampleinfo$prep == "Nikos" & 
                 sampleinfo$ctg %in% 3:4&
  !(sampleinfo$sample %in% c("O1a", "O1b", "YR1a", "YR1b" , "YR2a", "YR2b")))))


si <- subset(sampleinfo, sampleinfo$sample %in% colnames(md))


sl <- as.character(sampleinfo$sample[sampleinfo$sample %in% colnames(md)])

md$marker <- rownames(md)

mmd <- gather(as.data.frame(md), key="sample", value="expression", sl) 
mmd$gp <- substr(mmd$sample, 1, nchar(mmd$sample)-1)

mmd$rep <- substr(mmd$sample,  nchar(mmd$sample), nchar(mmd$sample))


md <- select(mmd, -sample) 


mmd2 <- left_join( select(dplyr::rename(filter(md, rep=="a"), expression_a =expression), -rep),
                   select(dplyr::rename(filter(md, rep=="b"), expression_b =expression), -rep),
                   by=c("marker", "gp") )


ggplot(mmd2, aes(x=expression_a, y=expression_b))+
  geom_point(alpha=0.1)+
  geom_smooth(method="lm")+
# geom_hex()+
  theme_bw()+
   scale_x_log10()+
  scale_y_log10()


ablm <- lm(expression_a~expression_b, data=mmd2)
summary(ablm)

mmd2$predexpa <- predict(ablm)
mmd2$resid <- mmd2$expression_a -mmd2$predexpa


mmd2$abfc <- foldchange2logratio(foldchange(mmd2$expression_a, mmd2$expression_b))
mmd2$absabfc <- abs(mmd2$abfc)
mmd2$normresid <- mmd2$resid/mmd2$expression_b

ggplot(mmd2, aes(y=normresid, x=expression_b))+
  geom_point(alpha=0.1)+
  stat_smooth()+
# geom_hex()+
  theme_bw()+
  scale_x_log10()




````




```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
reorder_cormat <- function(cormat){
# Use correlation between variables as distance
dd <- as.dist((1-cormat)/2)
hc <- hclust(dd)
cormat <-cormat[hc$order, hc$order]
}

 get_lower_tri<-function(cormat){
    cormat[upper.tri(cormat)] <- NA
    return(cormat)
  }
  # Get upper triangle of the correlation matrix
  get_upper_tri <- function(cormat){
    cormat[lower.tri(cormat)]<- NA
    return(cormat)
  }
  

mhk <- hkdat[, 1:5]
mhk <- mhk[ , order(names(mhk))]
cormat <- round(cor(mhk),2)  
  
cormat <- reorder_cormat(cormat)
upper_tri <- get_upper_tri(cormat)

mcm <- melt(cormat, na.rm = TRUE)



ggplot(data = mcm, aes(Var1, Var2, fill = value, label=value))+
 geom_tile(color = "white")+
    geom_text(colour="black")+
 scale_fill_gradient2(low = "red3", high = "cornflower blue", mid = "white", 
   midpoint = 0.5, limit = c(0,1), space = "Lab", 
   name="Pearson\nCorrelation") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()+
  xlab("")+
  ylab("")+
  ggtitle("Correlation between Housekeeping Genes")



````



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
ggpairs(mhk)+
  theme_bw()


````

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


log <-   !(sampleinfo$sample %in% c("AG", "AI", "AB")) &
  sampleinfo$flag == FALSE
#log <- TRUE

bcmin <- as.matrix(ctall.hk[,log==T])
bcmin.groups <- sampleinfo$flag[log==T]
tbc <- as.matrix(t(bcmin))
bc.pca <- prcomp(tbc,center = TRUE,scale. = TRUE) 
bc.groups <- bcmin.groups


ggbiplot(bc.pca, obs.scale = 1, var.scale = 1, ellipse = FALSE, circle = TRUE, var.axes=T, labels=rownames(tbc), groups=bc.groups)+ggtitle("PCA")+
    theme_minimal() +
  scale_colour_manual(values=c("cornflower blue", "red3", "black"))+
  theme(plot.title=element_text(size=8,face="bold"))
#  geom_label(label=rownames(tbc), aes(colour=bc.groups))+
#  scale_colour_manual(values= c("darkviolet","cornflower blue",  "red2"))


```

#Housekeeping genes to predict one another

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


log <-   !(sampleinfo$sample %in% c("AG", "AI", "AB")) &
  sampleinfo$flag == FALSE
#log <- TRUE

mhk <- as.data.frame(t(ctall.hk[,log==T])) 

colnames(mhk) <- substr(colnames(mhk),1,2)


lmhl <- lm(HL~., data=mhk)
lmeo <- lm(EO~., data=mhk)
lmfq <- lm(FQ~., data=mhk)
lmaq <- lm(AQ~., data=mhk)
lmbs <- lm(BS~., data=mhk)

mhk <-   rownames_to_column(mhk, var="sample")
allhk <- as.data.frame(t(ctall.hk)) 

colnames(allhk) <- substr(colnames(allhk),1,2)

allhk <- rownames_to_column(allhk, var="sample")

predf <- data.frame("HL"= predict(lmhl, newdata = allhk), 
                    "EO"= predict(lmeo, newdata = allhk),
                    "FQ"= predict(lmfq, newdata = allhk),
                    "AQ"= predict(lmaq, newdata = allhk),
                    "BS"= predict(lmbs, newdata = allhk), 
                    "sample"= allhk$sample) 

mpredf <- gather(predf, key= "hk", value="predexp", -sample)
mmhk <- gather(mhk, key="hk", value="exp", -sample) %>%
  left_join(mpredf, by=c("hk", "sample"))


mallhk <- gather(allhk, key="hk", value="exp", -sample) %>%
  left_join(mpredf, by=c("hk", "sample"))

hkm <- data.frame(mean= colMeans(t(ctall.hk[,log==T])), hk=substr(colnames(t(ctall.hk[,log==T])),1,2))


mmhk$resid <- mmhk$exp-mmhk$predexp

mallhk$resid <- mallhk$exp-mmhk$predexp
mallhk$flag <- mallhk$sample %in% sampleinfo$sample[  sampleinfo$flag == T]
mallhk <- left_join(mallhk, hkm, by= "hk")
mallhk$normresid <- mallhk$resid/mallhk$mean

ggplot(mmhk, aes(x=exp, y=predexp))+geom_point()+
  facet_wrap(~hk)+scale_y_log10()+
  scale_x_log10()+theme_bw()


ggplot(mallhk, aes(x=normresid, fill=flag))+
  geom_density(alpha=0.5)+
  theme_bw()+
scale_fill_brewer(palette="Set1")+
  facet_wrap(~hk)
  xlim(-300, 300)

````
