---
title: "regperm"
output: html_document
---

#Set-up & import


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(dplyr)
library(tibble)
library(tidyr)
library(caret)
library(RColorBrewer)
library(ggrepel)
library(gtools)
#library(FinCal)
library(ggrepel)
library(reshape2)



 rep.row<-function(x,n){
   matrix(rep(x,each=n),nrow=n)
 } 

#library(e10)
````



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
#setwd("~/Documents/nstringjul18/nstringfull")
load(file="allns_data.rdata")
load(file="modelrf.rdata")
load(file="modelgbm.rdata")
load(file="hkdat.rdata")
load(file="sampleinfo.rdata")
load(file="goodgroups.rdata")
load(file="vrimprf.rdata")

````




```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


#mymodel <- currbestgbm
mymodel <- gbmcompro
vrimpgbm <- summary(mymodel)


vrimpgbm$sname <- substr(vrimpgbm$var,1,2)
vrimpgbm$sname <- factor(vrimpgbm$sname, levels=vrimpgbm$sname[order(vrimpgbm$rel.inf, decreasing=T)])

(p=ggplot(vrimpgbm, aes(x=sname, y=rel.inf))+
  theme_bw()+
  geom_bar(stat="identity", fill="red3")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  xlab("Marker")+
  ylab("Contribution to model")+
  ggtitle("Marker contributions", subtitle= paste0("GBM model built with ", length(mymodel$coefnames), " markers"))
)
top50 <- as.character(vrimpgbm$var[order(vrimpgbm$rel.inf, decreasing =T)][1:50])

contriblist<- as.character(vrimpgbm$var)[vrimpgbm$rel.inf >0]

````
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


md <- as.data.frame(subset(t(ctall.norm), 
                           (sampleinfo$sex == "F" &
                 sampleinfo$exp %in% c("regen") & 
                  sampleinfo$ctg > 5 &
                   substr(sampleinfo$sample,1,1) %in% goodgroups &
                 sampleinfo$type %in% c("O", "Y", "M", "OR", "MR", "YR")
 )))

#mymodel <- currbest

#mymodel <- rfagemodel61
md <- md[, colnames(md) %in% mymodel$coefnames]

regs <- subset(md, substr(rownames(md),2,4) == "reg")
uns <- subset(md, substr(rownames(md),2,3) == "un")

reguns <- rbind(regs, uns)

r <- nrow(regs)
c <- ncol(regs)


 
 
mreguns <- melt(rownames_to_column(reguns))

colnames(mreguns) <- c("sample", "marker", "exp")
````

#Perm matrix

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
nperm <- 200

mm3<- data.frame(matrix(ncol = 4, nrow = 0))
colnames(mm3) <- c( "group" , "marker" ,"choice" ,"perm" )

qmm3 <- mm3
for (i in 1:ncol(reguns)){

#for (i in 1:3){
  
cm <- colnames(reguns)[i]



mm2<- data.frame(matrix(ncol = 4, nrow = 0))
colnames(mm2) <- c( "group" , "marker" ,"choice" ,"perm" )
for (j in 1:nperm){

m1 <- as.data.frame(round(matrix(runif(r*c), r, c)))


choices <-sample(c("reg", "un"), size=ncol(regs), replace=TRUE)
 
m1 <- as.data.frame(rep.row(choices,r))

colnames(m1) <- colnames(regs)
m1$group <- substr(rownames(regs),1,1)



mm1 <- gather(m1, key= marker, value="choice", -group)
mm1$perm <- j
mm2 <- rbind(mm2,mm1)
j

}

qmm2 <- mm2
mm2$choice[mm2$marker == cm] <- "reg"
mm2$sample <- paste0(mm2$group, mm2$choice)

qmm2$sample <- paste0(qmm2$group, qmm2$choice)



mm2$cm <- cm
qmm2$cm <- cm


mm3 <- rbind(mm2, mm3)
qmm3 <- rbind(qmm2, qmm3)

}

mm3 <- left_join(mm3, mreguns, by=c("sample", "marker"))

qmm3 <- left_join(qmm3, mreguns, by=c("sample", "marker"))


sm3 <- spread(select(mm3,-sample, -choice), value="exp", key="marker")

sm3$predage <- predict(mymodel, newdata= sm3[,colnames(sm3)%in% colnames(reguns)])


qsm3 <- spread(select(qmm3,-sample, -choice), value="exp", key="marker")



sm3$predagecontrol <- predict(mymodel, newdata= qsm3[,colnames(qsm3)%in% colnames(reguns)])


sm3$predagediff <- sm3$predage - sm3$predagecontrol


#qsm3$predage <- predict(mymodel, newdata= qsm3[,colnames(qsm3)%in% colnames(reguns)])

````

#Joins

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

````


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
reguns2 <-mutate(reguns, predage= predict(mymodel, newdata=reguns), 
                 state= substr(rownames(reguns),2,6), 
                 group = substr(rownames(reguns),1,1))


rvals <- select(reguns2, predage, state, group) %>%
  spread(value="predage", key="state")

# 
# 
# ggplot(sm3, aes(x=predage))+
#   geom_density()+
#   facet_grid(group~cm)+
#   geom_segment(data=reguns2, aes(x=predage, xend=predage, y=0, yend=0.1, colour=state),alpha=1, size=1.5)

````





```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

groupmeans <- dplyr::group_by(sm3, group)%>%
  dplyr::summarise(meanpredage = mean(predage), 
                   meandiff = mean(predagediff))





sm4 <- select(sm3, predage, predagediff, predagecontrol, group, perm, cm) %>%
  left_join(rvals, by="group")


msummar <- group_by(sm4, cm)%>%
  dplyr::summarise(cmmeandiff = mean(predagediff))%>%
  mutate(dir= cmmeandiff > 0)

sm4 <- left_join(sm4, msummar, by="cm")
sm4$cm <- factor(sm4$cm, levels=unique(sm4$cm[order(sm4$cmmeandiff)]))

msummar <- mutate(msummar, ma= substr(cm, 1,2)) %>%
                  left_join(vrimpgbm, by=c("ma"= "sname"))
sm4$ma <- substr(sm4$cm,1,2)

#sm4 <-  left_join(sm4,vrimprf, by=c("ma"= "sname"))

sm4 <-  left_join(sm4,vrimpgbm, by=c("ma"= "sname"))
```


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


sm4$ma <- factor(sm4$ma, levels=unique(sm4$ma[order(sm4$cmmeandiff)]))

#sm4$map <- paste0(sm4$ma, "\n", round(sm4$Overall,0))

ggplot(sm4, aes(y=predagediff, x=ma, fill=dir))+
  geom_boxplot()+
  ylim(-5,5)+
  geom_hline(yintercept = 0)+
#  facet_wrap(~cm)+
  theme_bw()+
 theme(axis.text.x = element_text(angle = 0, vjust = 1, 
    size = 5, hjust = 1))+
  scale_fill_manual(values=c("forest green", "orangered"), labels= c("Marker rejuvenates", "Marker ages"), name="Response to regeneration")+
  ylab("Distance from midpoint between regenerated and contralateral sample")+
  xlab("Marker gene")+
  ggtitle("Which markers rejuvenate?", 
          subtitle= paste0("Model type: ", toupper(mymodel$method), ", ", length(mymodel$coefnames), " markers used\n", 
                           nperm, " permutations"))
    

````

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

msummar$ma <- factor(msummar$ma, levels= msummar$ma[order(msummar$cmmeandiff)])


ggplot(msummar, aes(y=cmmeandiff, x= ma,size=rel.inf, fill=dir))+
  geom_point(shape=21)+
  geom_hline(yintercept = 0)+
#  facet_wrap(~cm)+
  theme_bw()+
  scale_fill_manual(values=c("forest green", "orangered"), labels= c("Marker rejuvenates", "Marker ages"), name="Response to regeneration")+
  ylab("Distance from midpoint between regenerated and contralateral sample")+
  xlab("Marker importance")+
  ggtitle("Which markers rejuvenate?", 
          subtitle= paste0("Model type: ", toupper(mymodel$method), ", ", length(mymodel$coefnames), " markers used\n", 
                           nperm, " permutations"))

```
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}




ggplot(msummar, aes(y=cmmeandiff, x=rel.inf, fill=dir))+
  geom_point(shape=21)+
#  ylim(-5,5)+
  geom_hline(yintercept = 0)+
#  facet_wrap(~cm)+
  theme_bw()+
  scale_x_continuous(trans="log2")+
  scale_fill_manual(values=c("forest green", "orangered"))+
  ylab("Distance from midpoint between regenerated and contralateral sample")+
  xlab("Marker importance")+
  ggtitle("Which markers rejuvenate?", 
          subtitle= paste0("Model type: ", toupper(mymodel$method), ", ", length(mymodel$coefnames), " markers used\n", 
                           nperm, " permutations"))+
  geom_smooth(aes(y=cmmeandiff, x=rel.inf), inherit.aes=F, method="lm", se=F)
# 
# ggplot(sm4, aes(y=meandiff, x=Overall, fill=dir))+
#   geom_point(alpha=0.02)+
# #  ylim(-5,5)+
#   geom_hline(yintercept = 0)+
# #  facet_wrap(~cm)+
#   theme_bw()+
#   scale_fill_manual(values=c("forest green", "orangered"))+
#   ylab("Distance from midpoint between regenerated and contralateral sample")+
#   ggtitle("Which markers rejuvenate?", 
#           subtitle= paste0("Model type: ", toupper(mymodel$method), ", ", length(mymodel$coefnames), " markers used\n", 
#                            nperm, " permutations"))    
```



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

sm4$ma <- factor(sm4$ma, levels=unique(sm4$ma[order(sm4$rel.inf)]))

(p=ggplot(sm4, aes(y=meandiff, x=ma, fill=dir))+
  geom_boxplot()+
  ylim(-5,5)+
  geom_hline(yintercept = 0)+
#  facet_wrap(~cm)+
  theme_bw()+
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 5, hjust = 1))+
  scale_fill_manual(values=c("forest green", "orangered"), labels= c("Marker rejuvenates", "Marker ages"), name="Response to regeneration")+
  ylab("Distance from midpoint between regenerated and contralateral sample")+
  xlab("Marker gene")+
  ggtitle("Which markers rejuvenate?", 
          subtitle= paste0("Model type: ", toupper(mymodel$method), ", ", length(mymodel$coefnames), " markers used\n", 
                           nperm, " permutations", "\nmarkers ordered by importance to model"))
)



````



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

sm4$ma <- factor(sm4$ma, levels=unique(sm4$ma[order(sm4$rel.inf)]))

ggplot(sm4, aes(y=meandiff, x=ma, fill=dir))+
    geom_point(aes(y=cmmeandiff))+
  geom_boxplot()+
  ylim(-5,5)+
  geom_hline(yintercept = 0)+
#  facet_wrap(~cm)+
  theme_bw()+
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 5, hjust = 1))+
  scale_fill_manual(values=c("forest green", "orangered"), labels= c("Marker rejuvenates", "Marker ages"), name="Response to regeneration")+
  ylab("Distance from midpoint between regenerated and contralateral sample")+
  xlab("Marker gene")+
  ggtitle("Which markers rejuvenate?", 
          subtitle= paste0("Model type: ", toupper(mymodel$method), ", ", length(mymodel$coefnames), " markers used\n", 
                           nperm, " permutations", "\nmarkers ordered by importance to model"))
)



````


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
save(sm3, sm4, file="permsrf.rdata")

````


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


````


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


````


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


````


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


````



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


````