---
title: "Aging effect"
author: "Luke Hayden"
date: "August 3, 2018"
output: html_document
---
#Set-up and data import


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(dplyr)
library(ggbiplot)
library(tibble)
library(tidyr)
library(caret)
library(RColorBrewer)
library(ggrepel)
library(gtools)
library(FinCal)
````




```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
setwd("~/Documents/nstringjul18")
load(file="allns_data.rdata")


save(cvdf,lmdf, lmdf2,  file="vardat.rdata")
load(file="vardat.rdata")

````


###Random forest


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

md <- as.data.frame(subset(t(ctall.norm), sampleinfo$sex == "F" &
#               sampleinfo$qual == "ok"& 
                 sampleinfo$prep== "Luke"&
                 sampleinfo$exp %in% c("Size-age", "cohorts", "OvY", "regen") & 
 #                sampleinfo$ctg>2 & 
                sampleinfo$codeset == "phaw_1" &
                 sampleinfo$type %in% c("O", "Y", "M")
&   !(sampleinfo$sample %in% c("T","C", "U", "LFPD", "O1a", "SFPA", "LFIB","LFIA","AF", "Coh8"))
))

#md <- md[,minf$chosenand ==T]
md <- md[, lmdf2$in61 ==T & lmdf2$pvalovy < 0.05] 


md$sample <- rownames(md)

md <- left_join(md, select(sampleinfo, sample, predage), by="sample") %>%
  filter(!(is.na(predage))) %>%
  column_to_rownames(var="sample")


trainchoice <- sample(1:nrow(md))[1:floor(4*(nrow(md)/5))]


#trainchoice <- rownames(md) %in% rownames(currbest$trainingData)
trdat <- md[trainchoice,]
tedat <- md[-trainchoice,]



rfagemodel <- train(
  predage~.,
  tuneLength = 4,
  metric="RMSE",
  data = trdat, method = "ranger",
  tuneGrid=expand.grid(mtry=c(10:20), 
                        splitrule=c("extratrees", "variance"),
                        min.node.size=c(1:10)),
  trControl = trainControl(method = "cv", number = 40, verboseIter = T)
)
```




```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

rfagemodel$trainingData
rfagemodel
````

##Model accuracy: age from body length regression


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
mymodel <- currbest
mymodel <- rfagemodel

md <- as.data.frame(subset(t(ctall.norm), sampleinfo$sex == "F" &
#               sampleinfo$qual == "ok"& 
                 sampleinfo$prep== "Luke"&
                 sampleinfo$exp %in% c("Size-age", "cohorts", "OvY", "regen") & 
 #                sampleinfo$ctg>2 & 
                sampleinfo$codeset == "phaw_1" &
                 sampleinfo$type %in% c("O", "Y", "M")& 
  !(sampleinfo$sample %in% c("T","C", "U", "LFPD", "O1a", "SFPA", "LFIB","LFIA","AF", "Coh8"))))



md <- md[,colnames(md) %in% mymodel$coefnames]



md$rfagepred <- predict(mymodel, newdata=md)


md$intrain <- rownames(md) %in% rownames(mymodel$trainingData)



md <- md %>%
  rownames_to_column(var="sample") %>%
  left_join(sampleinfo,  by="sample")

md <- subset(md, !(is.na(md$predage)))


#md$rfagepred <- predict(rfagemodel, newdata=md)

accrf <- lm(predage~rfagepred, subset(md, md$intrain==F))



(RMSEtr <- sqrt(mean( (md$rfagepred[md$intrain == T] - md$predage[md$intrain == T])   ^2)))


(RMSEte <- sqrt(mean( (md$rfagepred[md$intrain == F] - md$predage[md$intrain == F])   ^2)))

ggplot(md, aes(x=predage, y=rfagepred,colour=intrain))+
  geom_point()+
  xlab("Age (weeks) from body length") +
  ylab("Age (weeks) from marker gene expression (random forest model)")+
  geom_smooth(method="lm", colour="black")+
  theme_bw()+
 scale_colour_manual(values=c("cornflower blue", "red3"), name="Data partition", labels=c("Test", "Training"))+
  geom_text_repel(aes(label=sample), size=2.5)+
  ggtitle("Using Marker gene expression to predict age", 
          subtitle=paste0("RMSE in training data: ", round(RMSEtr,3), 
                          "\nRMSE in test data: ", round(RMSEte,3)))#+  facet_wrap(~intrain)



```


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
save(currbest, rfagemodel22, rfagemodel, file="models.rdata")

```

###Random forest: current best attempt


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

md <- as.data.frame(subset(t(ctall.norm), sampleinfo$sex == "F" &
#               sampleinfo$qual == "ok"& 
                 sampleinfo$prep== "Luke"&
                 sampleinfo$exp %in% c("Size-age", "cohorts", "OvY") & 
 #                sampleinfo$ctg>2 & 
                sampleinfo$codeset == "phaw_1" &
                 sampleinfo$type %in% c("O", "Y", "M")
&   !(sampleinfo$sample %in% c("T","C", "U", "LFPD", "O1a", "SFPA", "LFIB","LFIA","AF", "Coh8"))
))

#md <- md[,minf$chosenand ==T]
md <- md[, lmdf2$in61 ==T & lmdf2$pvalovy < 0.05] 


md$sample <- rownames(md)

md <- left_join(md, select(sampleinfo, sample, predage), by="sample") %>%
  filter(!(is.na(predage))) %>%
  column_to_rownames(var="sample")


trainchoice <- sample(1:nrow(md))[1:floor(4*(nrow(md)/5))]


trainchoice <- rownames(md) %in% rownames(currbest$trainingData)
trdat <- md[trainchoice,]
tedat <- md[-trainchoice,]



rfagemodel <- train(
  predage~.,
  tuneLength = 4,
  metric="RMSE",
  data = trdat, method = "ranger",
  tuneGrid=expand.grid(mtry=c(10:20), 
                        splitrule=c("extratrees", "variance"),
                        min.node.size=c(1:10)),
  trControl = trainControl(method = "cv", number = 40, verboseIter = T)
)
```


##Model accuracy: cohort age data

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

  
ggplot(md, aes(x=wkage, y=rfagepred))+
  geom_point(aes(colour=intrain))+
  xlab("Age (weeks): cohorts") +
  ylab("Age (weeks) from marker gene expression (random forest model)")+
  geom_smooth(method="lm", colour="black")+
  theme_bw()+
 scale_colour_manual(values=c("darkviolet", "cornflower blue", "red3"))+
  geom_text_repel(aes(label=sample,colour=type), size=2.5)+
  ggtitle("Using Marker gene expression to predict age", subtitle=paste("R^2 of correlation between actual age and \npredicted age based on gene expression with random forest model:", round(summary(lm(as.numeric(wkage)~rfagepred, md))$r.squared, 3)))




save(rfagemodel, file="rfagemodel.rdata")

```

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}





md <- as.data.frame(subset(t(ctall.norm), sampleinfo$sex == "F" &
                 sampleinfo$exp %in% c("Size-age", "cohorts", "OvY", "regen") & 
               sampleinfo$codeset == "phaw_1" &
                  sampleinfo$qual != "bad"&
#                  sampleinfo$over10reads >70 &
                 sampleinfo$type %in% c("O", "Y", "M", "OR", "MR", "YR")& 
  !(sampleinfo$sample %in% c("T","C", "U", "LFPD","Areg","Xreg", "O1a", "SFPA", "LFIB","LFIA","AF", "Coh8"))))


md$rfagepred <- predict(rfagemodel, newdata= md)




md$sample <- rownames(md)

md <- left_join(md, sampleinfo, by="sample") %>%
  filter(!(is.na(predage)))

md$type <- as.character(md$type)
md$type <- as.factor(case_when(
  md$type %in% c("O", "M", "Y") ~ as.character(md$type), 
  md$type %in% c("MR", "YR", "OR") ~"R"
))


lm <- lm(rfagepred~predage, data=md)
md$lmresid <- lm$residuals
md$lmressign <- md$lmresid >0

ggplot(md, aes(x=predage, y=rfagepred))+
  geom_point(aes(colour=type))+
  xlab("Age (weeks) from body length") +
  ylab("Age (weeks) from marker gene expression (random forest model)")+
  geom_smooth(method="lm", colour="black")+
  theme_bw()+
 scale_colour_manual(values=c("darkviolet", "cornflower blue", "forest green", "red2"), name="")+
  geom_text_repel(aes(label=sample,colour=type), size=2.5)+
  ggtitle("How does regeneration affect molecular age?")


t.test(md$lmresid[md$reg =="R"] , alternative="less" )
  

````



###Random forest
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

md <- as.data.frame(subset(t(ctallgood.norm), sampleinfo$sex == "F" &
  #              sampleinfo$qual == "ok"& 
                 sampleinfo$exp %in% c("Size-age", "cohorts", "OvY") & 
 #                sampleinfo$ctg>2 & 
                sampleinfo$codeset == "phaw_1" &
                 sampleinfo$type %in% c("O", "Y", "M")& 
  !(sampleinfo$sample %in% c("T","C", "U", "LFPD", "O1a", "SFPA", "LFIB","LFIA","AF", "Coh8"))))
md$sample <- rownames(md)

md <- left_join(md, select(sampleinfo, sample, predage), by="sample") %>%
  filter(!(is.na(predage))) %>%
  column_to_rownames(var="sample")

mtry <- seq(5,15, length.out = 3)

min.node.size <- seq(5,25, length.out = 5)

splitrule= c("extratrees", "variance")



tunegrid <- expand.grid(mtry=mtry, splitrule=splitrule, min.node.size=min.node.size)


rfagemodel <- train(
  predage~.,
  tuneLength = 4,
  data = md, method = "ranger",tuneGrid=tunegrid,
  trControl = trainControl(method = "cv",number = 5, verboseIter = T)
)

rfagemodel
#print("random forest:")
#summary(rfagemodel)
#plot(rfagemodel)

```

##Model accuracy: age from body length regression


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
md$rfagepred <- predict(rfagemodel)

md <- md %>%
  rownames_to_column(var="sample") %>%
  left_join(select(sampleinfo, -predage), by="sample")


accrf <- lm(predage~rfagepred, md)


ggplot(md, aes(x=predage, y=rfagepred))+
  geom_point(aes(colour=type))+
  xlab("Age (weeks) from body length") +
  ylab("Age (weeks) from marker gene expression (random forest model)")+
  geom_smooth(method="lm", colour="black")+
  theme_bw()+
 scale_colour_manual(values=c("darkviolet", "cornflower blue", "red3"))+
  geom_text_repel(aes(label=sample,colour=type), size=2.5)+
  ggtitle("Using Marker gene expression to predict age", subtitle=paste("R^2 of correlation between measure from length and from gene expression:", round(summary(accrf)$r.squared, 3)))


```


##Model accuracy: cohort age data

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

  
ggplot(md, aes(x=wkage, y=rfagepred))+
  geom_point(aes(colour=type))+
  xlab("Age (weeks): cohorts") +
  ylab("Age (weeks) from marker gene expression (random forest model)")+
  geom_smooth(method="lm", colour="black")+
  theme_bw()+
 scale_colour_manual(values=c("darkviolet", "cornflower blue", "red3"))+
  geom_text_repel(aes(label=sample,colour=type), size=2.5)+
  ggtitle("Using Marker gene expression to predict age", subtitle=paste("R^2 of correlation between actual age and predicted age based on gene expression with random forest model:", round(summary(lm(as.numeric(wkage)~rfagepred, md))$r.squared, 3)))




save(rfagemodel, file="rfagemodel.rdata")

```

So we can use our marker set to very accurately predict a sample's age. 

#Interrogating the model


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
summary(rfagemodel)
print(rfagemodel)
```

