---
title: "Gradient boosting"
output: html_document
---




```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

#Set-up and data import
library(dplyr)
library(tibble)
library(tidyr)
library(caret)
library(RColorBrewer)
library(ggrepel)
library(gtools)
#library(FinCal)
````




```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
#setwd("~/Documents/nstringjul18")
load(file="allns_data.rdata")
load("modelgbm.rdata")
load("models.rdata")
load("vardat.rdata")

load(file="qualitydat.rdata")
load(file="sampleinfo.rdata")
load(file="markerchoiceinfo.rdata")

load(file="gbmnew.rdata")


load(file="gbmrsq.rdata")

````

#Choose model samples
```{r Gradient boosting build, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

md <- as.data.frame(subset(t(ctall.norm), sampleinfo$sex == "F" &
#               sampleinfo$qual == "ok"&
                 sampleinfo$prep== "Luke"&
                 sampleinfo$exp %in% c("Size-age", "cohorts", "OvY") &
 #                sampleinfo$ctg>2 &
                sampleinfo$codeset == "phaw_1" &
                 sampleinfo$type %in% c("O", "Y", "M")
))

md <- subset(md, rownames(md)%in% qualsum$sample[qualsum$good])

md <- md[, lmdf2$in61 ==T & lmdf2$pvalovy < 0.05]

#md <- md[, lmdf2$in61 ==T & lmdf2$rsq > -0.01 &lmdf2$pvalovy < 0.05]
md <- md[, colnames(md) %in% c(minf$name[minf$in61==T], "predage")]

#md <- md[, colnames(md) %in% c(top50, "predage")]


md$sample <- rownames(md)

md <- left_join(md, select(sampleinfo, sample, predage), by="sample") %>%
  filter(!(is.na(predage))) %>%
  column_to_rownames(var="sample")


````


```{r Gradient boosting build, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


md1 <- subset(md, md$predage < quantile(md$predage)[2])
trainchoice <- sample(1:nrow(md1))[1:ceiling(4*(nrow(md1)/5))]
c1<- md1[trainchoice,]

md1 <- subset(md, md$predage < quantile(md$predage)[3] & md$predage >= quantile(md$predage)[2])
trainchoice <- sample(1:nrow(md1))[1:ceiling(4*(nrow(md1)/5))]
c2<- md1[trainchoice,]


md1 <- subset(md, md$predage < quantile(md$predage)[4]& md$predage >= quantile(md$predage)[3])
trainchoice <- sample(1:nrow(md1))[1:ceiling(4*(nrow(md1)/5))]
c3<- md1[trainchoice,]


md1 <- subset(md, md$predage >= quantile(md$predage)[4])

trainchoice <- sample(1:nrow(md1))[1:ceiling(4*(nrow(md1)/5))]
c4<- md1[trainchoice,]


trdat <- rbind(c1, c2, c3, c4)
  
  

````

#Train/test split
```{r Gradient boosting build, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

trainchoice <- rownames(md) %in% rownames(currbest$trainingData)
trdat <- md[trainchoice,]
#trdat <- gbmrsq3$trainingData


```

#Train GBM
```{r Gradient boosting build, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


gbmagemodelnew <- train(
  predage~.,
  tuneLength = 4,
  data = trdat, 
  method = "gbm",
  metric="Rsquared",
  
  tuneGrid=expand.grid(n.trees = (0:50)*100, 
                       interaction.depth = c(1,2,3,4,5), 
                       shrinkage = c(0.0001,.001, 0.01, 0.1) ,
                       n.minobsinnode = c(2,3,4,5,6,7)),
  trControl =  trainControl(method = 'cv', 
                            number = 7, 
                            summaryFunction=defaultSummary, 
                            verboseIter = F)
)

# 
# 
# train.formula(form = predage ~ ., 
#               data = trdat, 
#               tuneLength = 4, 
#     method = "gbm", 
#     tuneGrid = expand.grid(
#       n.trees = (0:50) *         100, 
#         interaction.depth = c(1, 2, 3, 4, 5), 
#       shrinkage = c(1e-04, 
#         0.001, 0.01, 0.1), 
#       n.minobsinnode = c(2, 3, 4, 5, 6, 
#         7)), trControl = trainControl(method = "cv", number = 7, 
#         summaryFunction = defaultSummary, verboseIter = T))
```


